{
 "title": "Granular Node Exporter Dashboard",
 "tags": [ "node_exporter" ],
 "time": { "from": "2025-08-25T03:23:00.000Z", "to": "2025-08-25T05:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "DS_DATA_SOURCE", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Selected job",
    "query": {
     "query": "label_values(node_cpu_seconds_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Selected instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=\"$job\"},instance)"
    }
   },
   { "name": "range", "label": "Selected range", "query": "5s" },
   {
    "name": "logical_cpu",
    "label": "selected instance logical cpu",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=\"$job\", instance=\"$instance\"},cpu)"
    }
   },
   {
    "name": "logical_cpu_count",
    "label": "Selected instance logical cpu count",
    "query": {
     "query": "query_result(scalar(count(count (node_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}) by (cpu))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance info: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logical cpu count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$logical_cpu_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "description": "Instance disk usage",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n    (\n    sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"}) - sum    (node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"})\n    ) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\", instance=\"$instance\"} - node_boot_time_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total swap memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"}) - sum(node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|devtmpfs|proc|sysfs\", job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu usage for instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Selected Instance cpu usage per logical cpu",
   "type": "timeseries",
   "description": "Instance cpu usage per logical cpu outside idle mode",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum( rate(node_cpu_seconds_total{job=\"$job\", instance=\"$instance\", mode!=\"idle\"}[$range]) ) by (cpu)",
     "legendFormat": "Cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "Selected instance cpu-$logical_cpu usage per mode",
   "type": "timeseries",
   "description": "Selected logical cpu (cpu-$logical_cpu) usage per mode for $instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(node_cpu_seconds_total{job=\"$job\", instance=\"$instance\", cpu=\"$logical_cpu\"}[$range])",
     "legendFormat": "mode {{mode}}"
    }
   ]
  },
  {
   "title": "Average cpu load over time for $logical_cpu_count logical cpu",
   "type": "timeseries",
   "description": "Selected instance cpu load for 1 min over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory usage for instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Ram usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((node_memory_MemTotal_bytes{job=\"$job\", instance=\"$instance\"} - node_memory_MemAvailable_bytes{job=\"$job\", instance=\"$instance\"}) / node_memory_MemTotal_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cpu usage across instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage per instance per job",
     "type": "timeseries",
     "description": "Cpu usage per instance exclude time in idle mode grouped by job",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum ( rate(node_cpu_seconds_total{mode!=\"idle\"}[$range]) ) by (instance, job) / count(node_cpu_seconds_total{mode=\"idle\"}) by (instance, job)",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Cpu usage per instance for job $job",
     "type": "timeseries",
     "description": "Cpu usage per instance exclude time in idle mode for $job",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum ( rate(node_cpu_seconds_total{mode!=\"idle\", job=\"$job\"}[$range]) ) by (instance, job) / count(node_cpu_seconds_total{mode=\"idle\"}) by (instance, job)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance count over time - Node exporter",
     "type": "timeseries",
     "description": "Instance count in the cluster with node exporter over time per job and overall ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(count (node_cpu_seconds_total) by (instance))",
       "legendFormat": "Total unique instances with node exporter "
      },
      {
       "expr": "count(count (node_cpu_seconds_total) by (job, instance)) by (job)",
       "legendFormat": "{{job}} node exporter instances"
      }
     ]
    },
    {
     "title": "Total instaces over time",
     "type": "timeseries",
     "description": "Total instances over time in the cluster grouped by prometheus job",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "count(up) by (job)", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Healthy instances over time",
     "type": "timeseries",
     "description": "Healthy instance count over time grouped by prometheus job",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "count (up==1) by (job)", "legendFormat": "{{job}}" }
     ]
    }
   ]
  }
 ]
}